version: "3"
services:
  jupyther:
    image : ronen567/jupyter-tensorflow
    build : .
    environment: 
      JUPYTER_ENABLE_LAB: 'yes'
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'

    volumes:  
      - /home/ronen:/home/jovyan
          
    container_name: jupyter
    ports:
      - "8888:8888"

